# -*- coding: utf-8 -*-
"""t2_clinical_analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zTtAMNRroEz4zbUhUYLBgHK68YBB_dtX
"""

import pandas as pd

import os
import os

print(os.getcwd())
print(os.listdir("/content"))

conditions = pd.read_csv("/content/conditions.csv")

import os

for file in [
    "conditions.csv",
    "observations.csv",
    "medications.csv",
    "procedures.csv",
    "allergies.csv"
]:
    print(file, "→", os.path.exists("/" + file))

conditions = pd.read_csv("/content/conditions.csv")

conditions

conditions.info()

conditions.head()

conditions.nunique()

conditions.isna().sum()

conditions.columns.tolist()

encounters = pd.read_csv("/content/encounters.csv")

print("Encounters shape:", encounters.shape)
print("Encounters columns:", encounters.columns.tolist())

invalid_encounters = conditions[
    ~conditions["ENCOUNTER"].isin(encounters["Id"])
]

print("Invalid encounter references:", len(invalid_encounters))

conditions['ENCOUNTER'].head(10).tolist()

conditions['ENCOUNTER'].dtype

encounters["Id"].head(10).tolist()

encounters["Id"].dtype

conditions['ENCOUNTER'].nunique()

encounters["Id"].nunique()

common = set(conditions["ENCOUNTER"]) & set(encounters["Id"])

print("Matching encounter IDs:", len(common))

unmatched = conditions[
    ~conditions["ENCOUNTER"].isin(encounters["Id"])
]

print("Unmatched rows:", len(unmatched))

print("Unique unmatched encounter IDs:", unmatched["ENCOUNTER"].nunique())

display(unmatched[["ENCOUNTER", "PATIENT", "CODE", "DESCRIPTION"]].head(20))

print("Sample valid encounter IDs:")
print(list(common)[:10])

print("\nSample unmatched encounter IDs:")
print(unmatched["ENCOUNTER"].head(10).tolist())



# Check whether (ENCOUNTER, CODE) is unique
duplicate_key = conditions.duplicated(
    subset=["ENCOUNTER", "CODE"],
    keep=False
)

print("Duplicate (ENCOUNTER, CODE) rows:", duplicate_key.sum())
print(
    "Duplicate (ENCOUNTER, CODE) combinations:",
    conditions.loc[duplicate_key, ["ENCOUNTER", "CODE"]]
    .drop_duplicates()
    .shape[0]
)

print("Missing ENCOUNTER:", conditions["ENCOUNTER"].isna().sum())
print("Missing CODE:", conditions["CODE"].isna().sum())

code_description = (
    conditions.groupby("CODE")["DESCRIPTION"]
    .nunique()
)

print("Codes with multiple descriptions:",
      (code_description > 1).sum())

print("Maximum descriptions for one code:",
      code_description.max())

observations = pd.read_csv("/content/observations.csv")

print("===== OBSERVATIONS PROFILE =====")

print("\n1. SHAPE")
print(observations.shape)

print("\n2. COLUMNS")
print(observations.columns.tolist())

print("\n3. DATA TYPES")
print(observations.dtypes)

print("\n4. MISSING VALUES")
print(observations.isna().sum())

print("\n5. UNIQUE VALUES")
print(observations.nunique())

print("\n6. SAMPLE RECORDS")
display(observations.head())

invalid_obs_patient_refs = observations[
    ~observations["PATIENT"].isin(patients["Id"])
]

print("Invalid Observations patient references:",
      len(invalid_obs_patient_refs))

print("Unique invalid patient IDs:",
      invalid_obs_patient_refs["PATIENT"].nunique())

obs_with_encounter = observations[
    observations["ENCOUNTER"].notna()
]

invalid_obs_encounters = obs_with_encounter[
    ~obs_with_encounter["ENCOUNTER"].isin(encounters["Id"])
]

print("Observations rows with ENCOUNTER:", len(obs_with_encounter))
print("Invalid encounter references:", len(invalid_obs_encounters))
print("Unique invalid encounter IDs:",
      invalid_obs_encounters["ENCOUNTER"].nunique())

matched_obs = observations[
    observations["ENCOUNTER"].isin(encounters["Id"])
].copy()

matched_obs = matched_obs.merge(
    encounters[["Id", "PATIENT"]],
    left_on="ENCOUNTER",
    right_on="Id",
    suffixes=("_observation", "_encounter")
)

patient_mismatch_obs = matched_obs[
    matched_obs["PATIENT_observation"] != matched_obs["PATIENT_encounter"]
]

print("Matched observation rows:", len(matched_obs))
print("Patient mismatches:", len(patient_mismatch_obs))

# Test composite key: (ENCOUNTER, CODE)

duplicate_obs_key = observations.duplicated(
    subset=["ENCOUNTER", "CODE"],
    keep=False
)

print("Duplicate (ENCOUNTER, CODE) rows:",
      duplicate_obs_key.sum())

print(
    "Duplicate (ENCOUNTER, CODE) combinations:",
    observations.loc[
        duplicate_obs_key,
        ["ENCOUNTER", "CODE"]
    ].drop_duplicates().shape[0]
)

print("Missing ENCOUNTER:",
      observations["ENCOUNTER"].isna().sum())

print("Missing CODE:",
      observations["CODE"].isna().sum())

duplicate_obs = observations[
    observations.duplicated(
        subset=["ENCOUNTER", "CODE"],
        keep=False
    )
].copy()

print("Duplicate rows:", len(duplicate_obs))

display(
    duplicate_obs[
        ["DATE", "PATIENT", "ENCOUNTER", "CATEGORY",
         "CODE", "DESCRIPTION", "VALUE", "UNITS", "TYPE"]
    ].head(30))

# Keep only observations where ENCOUNTER is present
obs_with_enc = observations[
    observations["ENCOUNTER"].notna()
].copy()

print("Rows with ENCOUNTER:", len(obs_with_enc))

duplicate_nonnull = obs_with_enc.duplicated(
    subset=["ENCOUNTER", "CODE"],
    keep=False
)

print("Duplicate (ENCOUNTER, CODE) rows when ENCOUNTER is present:",
      duplicate_nonnull.sum())

print(
    "Duplicate (ENCOUNTER, CODE) combinations:",
    obs_with_enc.loc[
        duplicate_nonnull,
        ["ENCOUNTER", "CODE"]
    ].drop_duplicates().shape[0]
)

duplicate_real_obs = obs_with_enc[
    obs_with_enc.duplicated(
        subset=["ENCOUNTER", "CODE"],
        keep=False
    )
]

display(
    duplicate_real_obs[
        ["DATE", "PATIENT", "ENCOUNTER", "CATEGORY",
         "CODE", "DESCRIPTION", "VALUE", "UNITS", "TYPE"]
    ].head(30)
)

duplicate_obs_date_key = observations.duplicated(
    subset=["ENCOUNTER", "CODE", "DATE"],
    keep=False
)

print(
    "Duplicate (ENCOUNTER, CODE, DATE) rows:",
    duplicate_obs_date_key.sum()
)

print(
    "Duplicate (ENCOUNTER, CODE, DATE) combinations:",
    observations.loc[
        duplicate_obs_date_key,
        ["ENCOUNTER", "CODE", "DATE"]
    ].drop_duplicates().shape[0]
)

print("Missing ENCOUNTER:",
      observations["ENCOUNTER"].isna().sum())

print("Missing CODE:",
      observations["CODE"].isna().sum())

print("Missing DATE:",
      observations["DATE"].isna().sum())

duplicate_real_obs = obs_with_enc[
    obs_with_enc.duplicated(
        subset=["ENCOUNTER", "CODE", "DATE"],
        keep=False
    )
].copy()

print("Rows duplicated on ENCOUNTER + CODE + DATE:",
      len(duplicate_real_obs))

display(
    duplicate_real_obs[
        ["DATE", "PATIENT", "ENCOUNTER", "CATEGORY",
         "CODE", "DESCRIPTION", "VALUE", "UNITS", "TYPE"]
    ].head(30)
)

# Test PATIENT + ENCOUNTER + CODE + DATE

duplicate_patient_key = observations.duplicated(
    subset=["PATIENT", "ENCOUNTER", "CODE", "DATE"],
    keep=False
)

print(
    "Duplicate (PATIENT, ENCOUNTER, CODE, DATE) rows:",
    duplicate_patient_key.sum()
)

print(
    "Duplicate combinations:",
    observations.loc[
        duplicate_patient_key,
        ["PATIENT", "ENCOUNTER", "CODE", "DATE"]
    ].drop_duplicates().shape[0]
)

duplicate_obs2 = observations[
    observations.duplicated(
        subset=["PATIENT", "ENCOUNTER", "CODE", "DATE"],
        keep=False
    )
].copy()

display(
    duplicate_obs2[
        ["DATE", "PATIENT", "ENCOUNTER",
         "CATEGORY", "CODE", "DESCRIPTION",
         "VALUE", "UNITS", "TYPE"]
    ].head(40)
)

duplicate_obs_value_key = observations.duplicated(
    subset=["PATIENT", "ENCOUNTER", "CODE", "DATE", "VALUE"],
    keep=False
)

print(
    "Duplicate (PATIENT, ENCOUNTER, CODE, DATE, VALUE) rows:",
    duplicate_obs_value_key.sum()
)

print(
    "Duplicate combinations:",
    observations.loc[
        duplicate_obs_value_key,
        ["PATIENT", "ENCOUNTER", "CODE", "DATE", "VALUE"]
    ].drop_duplicates().shape[0]
)

remaining_dups = observations[
    observations.duplicated(
        subset=["PATIENT", "ENCOUNTER", "CODE", "DATE", "VALUE"],
        keep=False
    )
].copy()

display(
    remaining_dups[
        ["DATE", "PATIENT", "ENCOUNTER",
         "CATEGORY", "CODE", "DESCRIPTION",
         "VALUE", "UNITS", "TYPE"]
    ].head(40)
)

exact_duplicates = observations.duplicated(
    keep=False
)

print("Exact duplicate rows:", exact_duplicates.sum())

print(
    "Exact duplicate combinations:",
    observations[exact_duplicates].drop_duplicates().shape[0]
)

print(
    "Rows after exact duplicate removal:",
    len(observations_no_exact_dups)
)

duplicate_key_after_cleaning = observations_no_exact_dups.duplicated(
    subset=["PATIENT", "ENCOUNTER", "CODE", "DATE", "VALUE"],
    keep=False
)

print(
    "Duplicate (PATIENT, ENCOUNTER, CODE, DATE, VALUE) rows:",
    duplicate_key_after_cleaning.sum()
)

print(
    "Duplicate combinations:",
    observations_no_exact_dups.loc[
        duplicate_key_after_cleaning,
        ["PATIENT", "ENCOUNTER", "CODE", "DATE", "VALUE"]
    ].drop_duplicates().shape[0]
)

observations_no_exact_dups = observations.drop_duplicates()

print("Original rows:", len(observations))
print("After exact-duplicate removal:", len(observations_no_exact_dups))
print(
    "Exact duplicate rows removed:",
    len(observations) - len(observations_no_exact_dups)
)

duplicate_key_after_cleaning = observations_no_exact_dups.duplicated(
    subset=["PATIENT", "ENCOUNTER", "CODE", "DATE", "VALUE"],
    keep=False
)

print(
    "Duplicate key rows after exact-duplicate removal:",
    duplicate_key_after_cleaning.sum()
)

print(
    "Duplicate key combinations:",
    observations_no_exact_dups.loc[
        duplicate_key_after_cleaning,
        ["PATIENT", "ENCOUNTER", "CODE", "DATE", "VALUE"]
    ].drop_duplicates().shape[0]
)

obs_no_encounter = observations[
    observations["ENCOUNTER"].isna()
].copy()

print("Rows with missing ENCOUNTER:", len(obs_no_encounter))

print("\nCATEGORY:")
print(obs_no_encounter["CATEGORY"].value_counts(dropna=False))

print("\nCODE:")
print(obs_no_encounter["CODE"].value_counts(dropna=False).head(20))

print("\nTYPE:")
print(obs_no_encounter["TYPE"].value_counts(dropna=False))

print("\nDESCRIPTION:")
print(obs_no_encounter["DESCRIPTION"].value_counts(dropna=False).head(20))

patient_level = observations[
    observations["ENCOUNTER"].isna()
].copy()

duplicate_patient_level = patient_level.duplicated(
    subset=["PATIENT", "DATE", "CODE"],
    keep=False
)

print(
    "Duplicate (PATIENT, DATE, CODE) rows:",
    duplicate_patient_level.sum()
)

print(
    "Duplicate combinations:",
    patient_level.loc[
        duplicate_patient_level,
        ["PATIENT", "DATE", "CODE"]
    ].drop_duplicates().shape[0]
)

code_description_obs = (
    observations.groupby("CODE")["DESCRIPTION"]
    .nunique()
)

print(
    "Codes with multiple descriptions:",
    (code_description_obs > 1).sum()
)

print(
    "Maximum descriptions for one code:",
    code_description_obs.max()
)

problem_codes_obs = code_description_obs[
    code_description_obs > 1
]

print("Problematic CODE(s):")
print(problem_codes_obs)

for code in problem_codes_obs.index:
    print("\nCODE:", code)
    display(
        observations[
            observations["CODE"] == code
        ][["CODE", "DESCRIPTION"]]
        .drop_duplicates()
    )

medications=pd.read_csv('/content/medications.csv')

medications.nunique()

medications.shape

medications.isna().sum()

medications.dtypes

medications.columns.tolist()

invalid_med_encounter=medications[~medications['ENCOUNTER'].isin(encounters['Id'])]

print("Invalid Medication encounter references:",
      len(invalid_med_encounter))

print("Unique invalid encounter IDs:",
      invalid_med_encounter["ENCOUNTER"].nunique())

print("Missing medication ENCOUNTER:",
      medications["ENCOUNTER"].isna().sum())

matched_medications = medications[
    medications["ENCOUNTER"].isin(encounters["Id"])
]

print("Matched medication rows:", len(matched_medications))

med_check = matched_medications.merge(
    encounters[["Id", "PATIENT"]],
    left_on="ENCOUNTER",
    right_on="Id",
    suffixes=("_medication", "_encounter")
)

mismatch = med_check[
    med_check["PATIENT_medication"] != med_check["PATIENT_encounter"]
]

print("Patient mismatches:", len(mismatch))

print(
    "Duplicate (PATIENT, CODE, START) rows:",
    medications.duplicated(
        subset=["PATIENT", "CODE", "START"],
        keep=False
    ).sum()
)

med_dups = medications[
    medications.duplicated(
        subset=["PATIENT", "CODE", "START"],
        keep=False
    )
]

display(
    med_dups[
        ["PATIENT", "ENCOUNTER", "CODE",
         "DESCRIPTION", "START", "STOP"]
    ].head(30)
)

med_key_test = medications.duplicated(
    subset=["PATIENT", "CODE", "START", "STOP"],
    keep=False
)

print(
    "Duplicate (PATIENT, CODE, START, STOP) rows:",
    med_key_test.sum()
)

print(
    "Duplicate combinations:",
    medications.loc[
        med_key_test,
        ["PATIENT", "CODE", "START", "STOP"]
    ].drop_duplicates().shape[0]
)

med_remaining_dups = medications[
    medications.duplicated(
        subset=["PATIENT", "CODE", "START", "STOP"],
        keep=False
    )
]

display(
    med_remaining_dups[
        ["PATIENT", "ENCOUNTER", "CODE",
         "DESCRIPTION", "START", "STOP"]
    ].sort_values(
        ["PATIENT", "CODE", "START", "STOP"]
    )
)

med_key_test2 = medications.duplicated(
    subset=["PATIENT", "ENCOUNTER", "CODE", "START", "STOP"],
    keep=False
)

print(
    "Duplicate (PATIENT, ENCOUNTER, CODE, START, STOP) rows:",
    med_key_test2.sum()
)

print(
    "Duplicate combinations:",
    medications.loc[
        med_key_test2,
        ["PATIENT", "ENCOUNTER", "CODE", "START", "STOP"]
    ].drop_duplicates().shape[0]
)

print(
    medications[
        ["PATIENT", "ENCOUNTER", "CODE", "START", "STOP"]
    ].isna().sum()
)

check3=medications.duplicated(subset=['PATIENT','ENCOUNTER','CODE','START'],keep=False)
check3.sum()

id="9h2k7m"
missing_stop = medications[medications["STOP"].isna()]

print("Rows with missing STOP:", len(missing_stop))

print(
    "Duplicate rows among missing STOP:",
    missing_stop.duplicated(
        subset=["PATIENT", "ENCOUNTER", "CODE", "START"],
        keep=False
    ).sum()
)

code_description_med = (
    medications.groupby("CODE")["DESCRIPTION"]
    .nunique()
)

print(
    "Codes with multiple descriptions:",
    (code_description_med > 1).sum()
)

print(
    "Maximum descriptions for one code:",
    code_description_med.max()
)

code_desc_counts = (
    medications.groupby("CODE")["DESCRIPTION"]
    .nunique()
)

problem_codes = code_desc_counts[
    code_desc_counts > 1
].index

print("Problematic medication codes:")
print(problem_codes.tolist())

for code in problem_codes:
    print("\nCODE:", code)

    display(
        medications[
            medications["CODE"] == code
        ][["CODE", "DESCRIPTION"]]
        .drop_duplicates()
    )

print(
    "Missing CODE:",
    medications["CODE"].isna().sum()
)

print(
    "Missing DESCRIPTION:",
    medications["DESCRIPTION"].isna().sum()
)

med_desc_check = (
    medications.assign(
        DESCRIPTION_NORMALIZED=
        medications["DESCRIPTION"].str.lower()
    )
    .groupby("CODE")["DESCRIPTION_NORMALIZED"]
    .nunique()
)

print(
    "Codes with different descriptions after ignoring case:",
    (med_desc_check > 1).sum()
)

medications["START_DATE"] = pd.to_datetime(medications["START"])
medications["STOP_DATE"] = pd.to_datetime(medications["STOP"])

invalid_dates = medications[
    medications["STOP_DATE"].notna() &
    (medications["STOP_DATE"] < medications["START_DATE"])
]

print("STOP before START:", len(invalid_dates))

medications.duplicated(keep=False).sum()

procedures=pd.read_csv('/content/procedures.csv')

procedures.head(10)

procedures.shape

procedures.columns.tolist()

procedures.info()

procedures.duplicated(keep=False).sum()

procedures['PATIENT'].nunique()

print("Unique PATIENT values:", procedures["PATIENT"].nunique())
print("Unique ENCOUNTER values:", procedures["ENCOUNTER"].nunique())
print("Unique CODE values:", procedures["CODE"].nunique())

check1=['PATIENT','ENCOUNTER','CODE','START','STOP']
drop_duplicates=procedures.duplicated(subset=check1,keep=False)
drop_duplicates.sum()

check2 = ["PATIENT", "ENCOUNTER", "CODE", "START"]

duplicates = procedures.duplicated(
    subset=check2,
    keep=False
)

print("Duplicate key rows:", duplicates.sum())

invalid_encounter=procedures[~procedures['ENCOUNTER'].isin(encounters['Id'])]

print("Invalid Procedure encounter references:",
      len(invalid_encounter))

print("Unique invalid encounter IDs:",
      invalid_encounter["ENCOUNTER"].nunique())

procedures["START"] = pd.to_datetime(procedures["START"])
procedures["STOP"] = pd.to_datetime(procedures["STOP"])

invalid_dates = procedures[
    procedures["STOP"] < procedures["START"]
]

print("STOP before START:", len(invalid_dates))

invalid_dates[["PATIENT", "ENCOUNTER", "CODE", "DESCRIPTION", "START", "STOP"]]

procedures.groupby('CODE')['DESCRIPTION'].nunique().sum(0)

procedure_code_desc = (
    procedures.groupby("CODE")["DESCRIPTION"]
    .nunique()
)

problem_procedure_codes = procedure_code_desc[
    procedure_code_desc > 1
]

print(
    "Codes with multiple descriptions:",
    len(problem_procedure_codes)
)

print(problem_procedure_codes)

procedures[
    procedures["CODE"] == 171207006
][["CODE", "DESCRIPTION"]].drop_duplicates()

procedure_desc_check = (
    procedures.assign(
        DESCRIPTION_NORMALIZED=procedures["DESCRIPTION"].str.lower()
    )
    .groupby("CODE")["DESCRIPTION_NORMALIZED"]
    .nunique()
)

print(
    "Codes with different descriptions after ignoring case:",
    (procedure_desc_check > 1).sum()
)

procedures.isna().sum()

reason_mismatch = procedures[
    procedures["REASONCODE"].isna() !=
    procedures["REASONDESCRIPTION"].isna()
]

print("Reason code/description mismatch rows:",
      len(reason_mismatch))

print(
    "Exact duplicate rows:",
    procedures.duplicated(keep=False).sum()
)

allergies=pd.read_csv('/content/allergies.csv')

allergies.head(10)

allergies.isna().sum()

check1=allergies.duplicated(subset=['PATIENT','ENCOUNTER','CODE','START'],keep=False)
check1.sum()

invalid_allergy_patients = allergies[
    ~allergies["PATIENT"].isin(patients["Id"])
]

print(
    "Invalid allergy patient references:",
    len(invalid_allergy_patients)
)

invalid_allergy_encounters = allergies[
    ~allergies["ENCOUNTER"].isin(encounters["Id"])
]

print(
    "Invalid allergy encounter references:",
    len(invalid_allergy_encounters)
)

invalid_allergy_encounters = allergies[
    ~allergies["ENCOUNTER"].isin(encounters["Id"])
]

print(
    invalid_allergy_encounters[
        ["PATIENT", "ENCOUNTER", "CODE", "DESCRIPTION"]
    ].head(10)
)

print(
    "Unique invalid allergy encounter IDs:",
    invalid_allergy_encounters["ENCOUNTER"].nunique()
)

invalid_allergy_encounters[
    ["PATIENT", "ENCOUNTER"]
].drop_duplicates().head(10)

invalid_patients_with_encounters = invalid_allergy_encounters[
    invalid_allergy_encounters["PATIENT"].isin(encounters["PATIENT"])
]

print(
    "Invalid allergy rows whose patient exists in encounters:",
    len(invalid_patients_with_encounters)
)

allergy_code_desc = (
    allergies.groupby("CODE")["DESCRIPTION"]
    .nunique()
)

problem_allergy_codes = allergy_code_desc[
    allergy_code_desc > 1
]

print(
    "Codes with multiple descriptions:",
    len(problem_allergy_codes)
)

print(problem_allergy_codes)

print(
    "Exact duplicate rows:",
    allergies.duplicated(keep=False).sum()
)

allergies["START"] = pd.to_datetime(allergies["START"])
allergies["STOP"] = pd.to_datetime(allergies["STOP"])

invalid_allergy_dates = allergies[
    allergies["STOP"].notna() &
    (allergies["STOP"] < allergies["START"])
]

print(
    "STOP before START:",
    len(invalid_allergy_dates)
)